<a href="https://colab.research.google.com/github/OleksiiLatypov/DRU_Data_Science_Fundamentals/blob/main/test_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to complete this assignment
Complete 15 graded tasks below.

- Do not delete or rename the variables given before the inscription `#your code here`.
- Do not change the code in the last Notebook cell, it is required for the server check.

## Some important notes
- If you need to **calculate the number of "something"** that means we expect you to assign an Integer to the given variable
- If you need to **make a list of "something"** we expect you to assign a Python list with appropriate values to the given variable
- If you need to find a **specifi—Å player, day of the week, team, etc.** we expect you to assign a String with the full name of the entity to the given variable (`player_name`, day of week full name, `team_name`, etc.)

In [89]:
import pandas as pd

pd.set_option('display.max_column', None)

In [90]:
player_data = pd.read_csv("player_data.csv", index_col="Unnamed: 0")

In [92]:
player_data.head()

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154

**Task 1 (0.25 point).** Calculate the number of players with a height between 180 and 190 inclusive

In [93]:
players_180_190 = player_data[player_data['height'].between(180, 190)]

**Task 2 (0.25 point).** Calculate the number of players born in 1980. <br>

In [94]:
players_1980 = player_data[player_data['birthday'].apply(lambda x: x[:4] == '1980')].shape[0]

**Task 3 (0.25 point).** Make a list of the top 10 players with the highest weight sorted in descending order. If there are several players with the same weight put them in the lexicographic order by name.

In [39]:
highest_players = player_data.sort_values(by=['weight', 'player_name'], ascending=[False, True])
highest_players

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
5901,5908,148325,Kristof van Hout,185306,1987-02-09 00:00:00,208.28,243
10297,10313,27313,Tim Wiese,53012,1981-12-17 00:00:00,193.04,243
4879,4884,5044,Jeroen Verhoeven,137692,1980-04-30 00:00:00,198.12,227
4408,4412,27267,Ishmael Miller,169725,1987-03-05 00:00:00,193.04,225
1595,1598,101584,Cassio,167958,1987-06-06 00:00:00,195.58,220
...,...,...,...,...,...,...,...
1477,1480,163840,Caetano,199931,1991-04-20 00:00:00,165.10,123
2609,2612,103139,Diego Buonanotte,170719,1988-04-19 00:00:00,160.02,123
6843,6853,306631,Mariusz Rybicki,208095,1993-03-13 00:00:00,175.26,121
10938,10954,108461,Yohandry Orozco,202559,1991-03-19 00:00:00,165.10,121
5446,5453,97226,Juan Quero,171126,1984-10-17 00:00:00,157.48,117

**Task 4 (0.5 point).** Make a list of tuples containing years along with the number of players born in that year from 1980 up to 1990. <br>
**Structure example**: [(1980, 123), (1981, 140) ..., (1990, 83)] -> There were born 123 players in 1980, there were born 140 players in 1981 and etc.

In [88]:
years_df = pd.to_datetime(player_data['birthday'], errors='coerce')
years_df_1980_1990 = player_data[player_data['birthday'].between('1980', '1991', inclusive=True)]
#years_born_players = # Your code here
years_df_1980_1990.sort_values(by='birthday', ascending=False).head()
players_count_by_year = years_df_1980_1990.groupby('birthday').size().reset_index(name='count')
years_and_players = list(zip(players_count_by_year['birthday'], players_count_by_year['count']))
players_count_by_year
years_and_players

<ipython-input-88-9a60b1986611>:2: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  years_df_1980_1990 = player_data[player_data['birthday'].between('1980', '1991', inclusive=True)]

[('1980-01-01 00:00:00', 1),
 ('1980-01-03 00:00:00', 1),
 ('1980-01-04 00:00:00', 1),
 ('1980-01-05 00:00:00', 2),
 ('1980-01-06 00:00:00', 1),
 ('1980-01-08 00:00:00', 1),
 ('1980-01-09 00:00:00', 2),
 ('1980-01-11 00:00:00', 3),
 ('1980-01-16 00:00:00', 1),
 ('1980-01-18 00:00:00', 3),
 ('1980-01-19 00:00:00', 1),
 ('1980-01-21 00:00:00', 3),
 ('1980-01-22 00:00:00', 2),
 ('1980-01-25 00:00:00', 4),
 ('1980-01-26 00:00:00', 1),
 ('1980-01-27 00:00:00', 1),
 ('1980-01-29 00:00:00', 3),
 ('1980-01-30 00:00:00', 2),
 ('1980-01-31 00:00:00', 2),
 ('1980-02-01 00:00:00', 3),
 ('1980-02-02 00:00:00', 2),
 ('1980-02-03 00:00:00', 1),
 ('1980-02-06 00:00:00', 1),
 ('1980-02-07 00:00:00', 1),
 ('1980-02-08 00:00:00', 1),
 ('1980-02-09 00:00:00', 2),
 ('1980-02-10 00:00:00', 3),
 ('1980-02-11 00:00:00', 1),
 ('1980-02-12 00:00:00', 2),
 ('1980-02-13 00:00:00', 1),
 ('1980-02-14 00:00:00', 1),
 ('1980-02-17 00:00:00', 2),
 ('1980-02-18 00:00:00', 2),
 ('1980-02-20 00:00:00', 2),
 ('1980-02-21 00:00:00', 1),
 ('1980-02-23 00:00:00', 1),
 ('1980-02-25 00:00:00', 1),
 ('1980-02-27 00:00:00', 1),
 ('1980-02-28 00:00:00', 2),
 ('1980-02-29 00:00:00', 1),
 ('1980-03-01 00:00:00', 3),
 ('1980-03-02 00:00:00', 1),
 ('1980-03-03 00:00:00', 1),
 ('1980-03-04 00:00:00', 1),
 ('1980-03-06 00:00:00', 2),
 ('1980-03-08 00:00:00', 1),
 ('1980-03-09 00:00:00', 2),
 ('1980-03-10 00:00:00', 1),
 ('1980-03-11 00:00:00', 1),
 ('1980-03-14 00:00:00', 1),
 ('1980-03-15 00:00:00', 3),
 ('1980-03-16 00:00:00', 1),
 ('1980-03-18 00:00:00', 1),
 ('1980-03-19 00:00:00', 4),
 ('1980-03-20 00:00:00', 2),
 ('1980-03-21 00:00:00', 2),
 ('1980-03-27 00:00:00', 1),
 ('1980-03-28 00:00:00', 1),
 ('1980-03-29 00:00:00', 1),
 ('1980-03-30 00:00:00', 1),
 ('1980-03-31 00:00:00', 1),
 ('1980-04-01 00:00:00', 1),
 ('1980-04-02 00:00:00', 1),
 ('1980-04-04 00:00:00', 1),
 ('1980-04-05 00:00:00', 1),
 ('1980-04-08 00:00:00', 2),
 ('1980-04-09 00:00:00', 1),
 ('1980-04-10 00:00:00', 1),
 ('1980-04-13 00:00:00', 2),
 ('1980-04-14 00:00:00', 1),
 ('1980-04-15 00:00:00', 1),
 ('1980-04-16 00:00:00', 1),
 ('1980-04-17 00:00:00', 1),
 ('1980-04-18 00:00:00', 1),
 ('1980-04-19 00:00:00', 1),
 ('1980-04-20 00:00:00', 2),
 ('1980-04-22 00:00:00', 2),
 ('1980-04-23 00:00:00', 1),
 ('1980-04-24 00:00:00', 2),
 ('1980-04-25 00:00:00', 1),
 ('1980-04-26 00:00:00', 1),
 ('1980-04-27 00:00:00', 1),
 ('1980-04-30 00:00:00', 3),
 ('1980-05-02 00:00:00', 4),
 ('1980-05-03 00:00:00', 1),
 ('1980-05-05 00:00:00', 4),
 ('1980-05-06 00:00:00', 1),
 ('1980-05-08 00:00:00', 1),
 ('1980-05-09 00:00:00', 2),
 ('1980-05-10 00:00:00', 1),
 ('1980-05-12 00:00:00', 2),
 ('1980-05-14 00:00:00', 2),
 ('1980-05-17 00:00:00', 2),
 ('1980-05-18 00:00:00', 1),
 ('1980-05-19 00:00:00', 1),
 ('1980-05-20 00:00:00', 1),
 ('1980-05-21 00:00:00', 1),
 ('1980-05-22 00:00:00', 1),
 ('1980-05-23 00:00:00', 2),
 ('1980-05-25 00:00:00', 2),
 ('1980-05-26 00:00:00', 2),
 ('1980-05-27 00:00:00', 2),
 ('1980-05-28 00:00:00', 1),
 ('1980-05-29 00:00:00', 1),
 ('1980-05-30 00:00:00', 1),
 ('1980-05-31 00:00:00', 1),
 ('1980-06-02 00:00:00', 2),
 ('1980-06-03 00:00:00', 1),
 ('1980-06-08 00:00:00', 1),
 ('1980-06-09 00:00:00', 2),
 ('1980-06-10 00:00:00', 3),
 ('1980-06-11 00:00:00', 3),
 ('1980-06-12 00:00:00', 1),
 ('1980-06-13 00:00:00', 2),
 ('1980-06-15 00:00:00', 1),
 ('1980-06-16 00:00:00', 4),
 ('1980-06-18 00:00:00', 1),
 ('1980-06-19 00:00:00', 3),
 ('1980-06-20 00:00:00', 1),
 ('1980-06-21 00:00:00', 1),
 ('1980-06-23 00:00:00', 3),
 ('1980-06-24 00:00:00', 2),
 ('1980-06-26 00:00:00', 1),
 ('1980-06-27 00:00:00', 2),
 ('1980-06-28 00:00:00', 3),
 ('1980-06-29 00:00:00', 1),
 ('1980-06-30 00:00:00', 4),
 ('1980-07-01 00:00:00', 1),
 ('1980-07-02 00:00:00', 1),
 ('1980-07-04 00:00:00', 1),
 ('1980-07-05 00:00:00', 3),
 ('1980-07-07 00:00:00', 1),
 ('1980-07-08 00:00:00', 1),
 ('1980-07-10 00:00:00', 3),
 ('1980-07-11 00:00:00', 1),
 ('1980-07-13 00:00:00', 1),
 ('1980-07-14 00:00:00', 2),
 ('1980-07-15 00:00:00', 1),
 ('1980-07-17 00:00:00', 2),
 ('1980-07-21 00:00:00', 1),
 ('1980-07-22 00:00:00', 2),
 ('1980-07-23 00:00:00', 1),
 ('1980-07-25 00:00:00', 1),
 ('1980-07-26 00:00:00', 1),
 ('1980-07-27 00:00:00', 1),
 ('1980-07-28 00:00:00', 1),
 ('1980-07-30 00:00:00', 2),
 ('1980-07-31 00:00:00', 1),
 ('1980-08-01 00:00:00', 2),
 ('1980-08-02 00:00:00', 4),
 ('1980-08-04 00:00:00', 2),
 ('1980-08-05 00:00:00', 7),
 ('1980-08-06 00:00:00', 4),
 ('1980-08-09 00:00:00', 1),
 ('1980-08-10 00:00:00', 3),
 ('1980-08-11 00:00:00', 3),
 ('1980-08-12 00:00:00', 3),
 ('1980-08-13 00:00:00', 2),
 ('1980-08-15 00:00:00', 1),
 ('1980-08-16 00:00:00', 2),
 ('1980-08-17 00:00:00', 3),
 ('1980-08-18 00:00:00', 5),
 ('1980-08-19 00:00:00', 2),
 ('1980-08-20 00:00:00', 1),
 ('1980-08-22 00:00:00', 1),
 ('1980-08-24 00:00:00', 2),
 ('1980-08-26 00:00:00', 1),
 ('1980-08-28 00:00:00', 1),
 ('1980-08-29 00:00:00', 1),
 ('1980-08-30 00:00:00', 1),
 ('1980-08-31 00:00:00', 2),
 ('1980-09-01 00:00:00', 1),
 ('1980-09-02 00:00:00', 1),
 ('1980-09-03 00:00:00', 2),
 ('1980-09-04 00:00:00', 1),
 ('1980-09-05 00:00:00', 3),
 ('1980-09-06 00:00:00', 1),
 ('1980-09-07 00:00:00', 2),
 ('1980-09-08 00:00:00', 1),
 ('1980-09-10 00:00:00', 1),
 ('1980-09-11 00:00:00', 2),
 ('1980-09-12 00:00:00', 3),
 ('1980-09-13 00:00:00', 2),
 ('1980-09-14 00:00:00', 1),
 ('1980-09-15 00:00:00', 3),
 ('1980-09-16 00:00:00', 1),
 ('1980-09-17 00:00:00', 1),
 ('1980-09-18 00:00:00', 2),
 ('1980-09-19 00:00:00', 2),
 ('1980-09-20 00:00:00', 2),
 ('1980-09-22 00:00:00', 1),
 ('1980-09-24 00:00:00', 3),
 ('1980-09-25 00:00:00', 1),
 ('1980-09-27 00:00:00', 1),
 ('1980-09-28 00:00:00', 1),
 ('1980-09-29 00:00:00', 2),
 ('1980-10-01 00:00:00', 2),
 ('1980-10-02 00:00:00', 1),
 ('1980-10-03 00:00:00', 1),
 ('1980-10-04 00:00:00', 2),
 ('1980-10-05 00:00:00', 1),
 ('1980-10-06 00:00:00', 2),
 ('1980-10-07 00:00:00', 3),
 ('1980-10-10 00:00:00', 1),
 ('1980-10-11 00:00:00', 1),
 ('1980-10-12 00:00:00', 1),
 ('1980-10-13 00:00:00', 3),
 ('1980-10-14 00:00:00', 1),
 ('1980-10-15 00:00:00', 1),
 ('1980-10-16 00:00:00', 1),
 ('1980-10-19 00:00:00', 3),
 ('1980-10-23 00:00:00', 1),
 ('1980-10-24 00:00:00', 2),
 ('1980-10-26 00:00:00', 2),
 ('1980-10-27 00:00:00', 1),
 ('1980-10-28 00:00:00', 1),
 ('1980-10-29 00:00:00', 1),
 ('1980-10-30 00:00:00', 1),
 ('1980-10-31 00:00:00', 2),
 ('1980-11-02 00:00:00', 2),
 ('1980-11-04 00:00:00', 1),
 ('1980-11-05 00:00:00', 1),
 ('1980-11-06 00:00:00', 3),
 ('1980-11-07 00:00:00', 2),
 ('1980-11-08 00:00:00', 4),
 ('1980-11-09 00:00:00', 1),
 ('1980-11-10 00:00:00', 2),
 ('1980-11-11 00:00:00', 1),
 ('1980-11-12 00:00:00', 2),
 ('1980-11-16 00:00:00', 1),
 ('1980-11-17 00:00:00', 3),
 ('1980-11-18 00:00:00', 1),
 ('1980-11-20 00:00:00', 1),
 ('1980-11-21 00:00:00', 1),
 ('1980-11-22 00:00:00', 1),
 ('1980-11-24 00:00:00', 1),
 ('1980-11-25 00:00:00', 3),
 ('1980-11-26 00:00:00', 1),
 ('1980-11-28 00:00:00', 2),
 ('1980-11-29 00:00:00', 1),
 ('1980-11-30 00:00:00', 2),
 ('1980-12-02 00:00:00', 2),
 ('1980-12-03 00:00:00', 2),
 ('1980-12-04 00:00:00', 2),
 ('1980-12-06 00:00:00', 1),
 ('1980-12-07 00:00:00', 2),
 ('1980-12-09 00:00:00', 1),
 ('1980-12-10 00:00:00', 1),
 ('1980-12-11 00:00:00', 1),
 ('1980-12-12 00:00:00', 3),
 ('1980-12-13 00:00:00', 2),
 ('1980-12-14 00:00:00', 2),
 ('1980-12-17 00:00:00', 2),
 ('1980-12-20 00:00:00', 4),
 ('1980-12-23 00:00:00', 1),
 ('1980-12-24 00:00:00', 3),
 ('1980-12-27 00:00:00', 1),
 ('1980-12-29 00:00:00', 1),
 ('1981-01-01 00:00:00', 2),
 ('1981-01-02 00:00:00', 2),
 ('1981-01-06 00:00:00', 1),
 ('1981-01-08 00:00:00', 1),
 ('1981-01-09 00:00:00', 2),
 ('1981-01-11 00:00:00', 1),
 ('1981-01-14 00:00:00', 2),
 ('1981-01-15 00:00:00', 1),
 ('1981-01-16 00:00:00', 3),
 ('1981-01-17 00:00:00', 2),
 ('1981-01-19 00:00:00', 4),
 ('1981-01-20 00:00:00', 2),
 ('1981-01-21 00:00:00', 2),
 ('1981-01-22 00:00:00', 1),
 ('1981-01-23 00:00:00', 4),
 ('1981-01-24 00:00:00', 1),
 ('1981-01-25 00:00:00', 2),
 ('1981-01-26 00:00:00', 2),
 ('1981-01-27 00:00:00', 1),
 ('1981-01-28 00:00:00', 3),
 ('1981-01-29 00:00:00', 2),
 ('1981-01-30 00:00:00', 3),
 ('1981-01-31 00:00:00', 4),
 ('1981-02-03 00:00:00', 2),
 ('1981-02-04 00:00:00', 3),
 ('1981-02-05 00:00:00', 1),
 ('1981-02-06 00:00:00', 1),
 ('1981-02-07 00:00:00', 1),
 ('1981-02-08 00:00:00', 1),
 ('1981-02-10 00:00:00', 1),
 ('1981-02-11 00:00:00', 1),
 ('1981-02-12 00:00:00', 2),
 ('1981-02-13 00:00:00', 3),
 ('1981-02-14 00:00:00', 2),
 ('1981-02-15 00:00:00', 2),
 ('1981-02-16 00:00:00', 1),
 ('1981-02-18 00:00:00', 3),
 ('1981-02-19 00:00:00', 2),
 ('1981-02-20 00:00:00', 2),
 ('1981-02-23 00:00:00', 5),
 ('1981-02-25 00:00:00', 3),
 ('1981-02-26 00:00:00', 4),
 ('1981-02-27 00:00:00', 1),
 ('1981-02-28 00:00:00', 4),
 ('1981-03-03 00:00:00', 1),
 ('1981-03-04 00:00:00', 1),
 ('1981-03-06 00:00:00', 1),
 ('1981-03-07 00:00:00', 4),
 ('1981-03-10 00:00:00', 4),
 ('1981-03-11 00:00:00', 1),
 ('1981-03-12 00:00:00', 1),
 ('1981-03-13 00:00:00', 1),
 ('1981-03-14 00:00:00', 2),
 ('1981-03-15 00:00:00', 2),
 ('1981-03-16 00:00:00', 1),
 ('1981-03-17 00:00:00', 6),
 ('1981-03-18 00:00:00', 1),
 ('1981-03-19 00:00:00', 1),
 ('1981-03-20 00:00:00', 2),
 ('1981-03-22 00:00:00', 1),
 ('1981-03-23 00:00:00', 2),
 ('1981-03-24 00:00:00', 1),
 ('1981-03-25 00:00:00', 2),
 ('1981-03-26 00:00:00', 2),
 ('1981-03-27 00:00:00', 2),
 ('1981-03-29 00:00:00', 1),
 ('1981-03-31 00:00:00', 1),
 ('1981-04-01 00:00:00', 3),
 ('1981-04-04 00:00:00', 2),
 ('1981-04-06 00:00:00', 1),
 ('1981-04-07 00:00:00', 1),
 ('1981-04-09 00:00:00', 2),
 ('1981-04-12 00:00:00', 2),
 ('1981-04-14 00:00:00', 2),
 ('1981-04-16 00:00:00', 3),
 ('1981-04-18 00:00:00', 1),
 ('1981-04-21 00:00:00', 1),
 ('1981-04-23 00:00:00', 3),
 ('1981-04-24 00:00:00', 2),
 ('1981-04-25 00:00:00', 2),
 ('1981-04-26 00:00:00', 1),
 ('1981-04-29 00:00:00', 1),
 ('1981-04-30 00:00:00', 2),
 ('1981-05-01 00:00:00', 3),
 ('1981-05-02 00:00:00', 2),
 ('1981-05-03 00:00:00', 4),
 ('1981-05-04 00:00:00', 2),
 ('1981-05-05 00:00:00', 5),
 ('1981-05-06 00:00:00', 1),
 ('1981-05-07 00:00:00', 1),
 ('1981-05-08 00:00:00', 1),
 ('1981-05-09 00:00:00', 2),
 ('1981-05-10 00:00:00', 2),
 ('1981-05-11 00:00:00', 1),
 ('1981-05-13 00:00:00', 1),
 ('1981-05-15 00:00:00', 3),
 ('1981-05-16 00:00:00', 2),
 ('1981-05-17 00:00:00', 1),
 ('1981-05-18 00:00:00', 3),
 ('1981-05-20 00:00:00', 2),
 ('1981-05-21 00:00:00', 3),
 ('1981-05-23 00:00:00', 1),
 ('1981-05-24 00:00:00', 1),
 ('1981-05-25 00:00:00', 2),
 ('1981-05-26 00:00:00', 3),
 ('1981-05-27 00:00:00', 2),
 ('1981-05-29 00:00:00', 3),
 ('1981-05-30 00:00:00', 1),
 ('1981-05-31 00:00:00', 2),
 ('1981-06-01 00:00:00', 1),
 ('1981-06-02 00:00:00', 3),
 ('1981-06-04 00:00:00', 2),
 ('1981-06-06 00:00:00', 3),
 ('1981-06-07 00:00:00', 2),
 ('1981-06-09 00:00:00', 2),
 ('1981-06-10 00:00:00', 5),
 ('1981-06-11 00:00:00', 1),
 ('1981-06-12 00:00:00', 4),
 ('1981-06-13 00:00:00', 2),
 ('1981-06-14 00:00:00', 2),
 ('1981-06-15 00:00:00', 1),
 ('1981-06-16 00:00:00', 2),
 ('1981-06-17 00:00:00', 1),
 ('1981-06-18 00:00:00', 1),
 ('1981-06-20 00:00:00', 2),
 ('1981-06-22 00:00:00', 3),
 ('1981-06-23 00:00:00', 2),
 ('1981-06-25 00:00:00', 1),
 ('1981-06-26 00:00:00', 1),
 ('1981-06-27 00:00:00', 2),
 ('1981-06-29 00:00:00', 1),
 ('1981-06-30 00:00:00', 2),
 ('1981-07-02 00:00:00', 1),
 ('1981-07-03 00:00:00', 1),
 ('1981-07-07 00:00:00', 1),
 ('1981-07-08 00:00:00', 1),
 ('1981-07-10 00:00:00', 3),
 ('1981-07-13 00:00:00', 2),
 ('1981-07-15 00:00:00', 3),
 ('1981-07-16 00:00:00', 1),
 ('1981-07-19 00:00:00', 2),
 ('1981-07-20 00:00:00', 1),
 ('1981-07-21 00:00:00', 2),
 ('1981-07-22 00:00:00', 1),
 ('1981-07-26 00:00:00', 1),
 ('1981-07-27 00:00:00', 1),
 ('1981-07-28 00:00:00', 2),
 ('1981-07-29 00:00:00', 2),
 ('1981-07-31 00:00:00', 1),
 ('1981-08-01 00:00:00', 2),
 ('1981-08-03 00:00:00', 2),
 ('1981-08-05 00:00:00', 3),
 ('1981-08-06 00:00:00', 2),
 ('1981-08-07 00:00:00', 1),
 ('1981-08-09 00:00:00', 1),
 ('1981-08-10 00:00:00', 1),
 ('1981-08-12 00:00:00', 3),
 ('1981-08-13 00:00:00', 3),
 ('1981-08-14 00:00:00', 2),
 ('1981-08-16 00:00:00', 1),
 ('1981-08-18 00:00:00', 3),
 ('1981-08-19 00:00:00', 1),
 ('1981-08-20 00:00:00', 1),
 ('1981-08-23 00:00:00', 1),
 ('1981-08-25 00:00:00', 1),
 ('1981-08-26 00:00:00', 1),
 ('1981-08-27 00:00:00', 4),
 ('1981-08-28 00:00:00', 2),
 ('1981-08-29 00:00:00', 1),
 ('1981-08-30 00:00:00', 2),
 ('1981-09-02 00:00:00', 1),
 ('1981-09-03 00:00:00', 1),
 ('1981-09-04 00:00:00', 3),
 ('1981-09-05 00:00:00', 2),
 ('1981-09-06 00:00:00', 2),
 ('1981-09-08 00:00:00', 2),
 ('1981-09-09 00:00:00', 1),
 ('1981-09-10 00:00:00', 2),
 ('1981-09-11 00:00:00', 2),
 ('1981-09-12 00:00:00', 1),
 ('1981-09-13 00:00:00', 1),
 ('1981-09-14 00:00:00', 1),
 ('1981-09-17 00:00:00', 2),
 ('1981-09-18 00:00:00', 1),
 ('1981-09-19 00:00:00', 3),
 ('1981-09-21 00:00:00', 1),
 ('1981-09-24 00:00:00', 2),
 ('1981-09-25 00:00:00', 1),
 ('1981-09-26 00:00:00', 2),
 ('1981-09-27 00:00:00', 1),
 ('1981-09-28 00:00:00', 3),
 ('1981-09-29 00:00:00', 2),
 ('1981-09-30 00:00:00', 2),
 ('1981-10-01 00:00:00', 2),
 ('1981-10-02 00:00:00', 3),
 ('1981-10-03 00:00:00', 2),
 ('1981-10-04 00:00:00', 1),
 ('1981-10-05 00:00:00', 1),
 ('1981-10-06 00:00:00', 2),
 ('1981-10-08 00:00:00', 2),
 ('1981-10-09 00:00:00', 3),
 ('1981-10-10 00:00:00', 1),
 ('1981-10-11 00:00:00', 1),
 ('1981-10-12 00:00:00', 2),
 ('1981-10-15 00:00:00', 1),
 ('1981-10-16 00:00:00', 1),
 ('1981-10-17 00:00:00', 1),
 ('1981-10-19 00:00:00', 1),
 ('1981-10-20 00:00:00', 2),
 ('1981-10-21 00:00:00', 1),
 ('1981-10-23 00:00:00', 1),
 ('1981-10-25 00:00:00', 2),
 ('1981-10-30 00:00:00', 1),
 ('1981-11-03 00:00:00', 2),
 ('1981-11-04 00:00:00', 1),
 ('1981-11-06 00:00:00', 1),
 ('1981-11-07 00:00:00', 1),
 ('1981-11-08 00:00:00', 3),
 ('1981-11-09 00:00:00', 2),
 ('1981-11-11 00:00:00', 2),
 ('1981-11-12 00:00:00', 3),
 ('1981-11-15 00:00:00', 1),
 ('1981-11-16 00:00:00', 2),
 ('1981-11-17 00:00:00', 1),
 ('1981-11-19 00:00:00', 2),
 ('1981-11-20 00:00:00', 1),
 ('1981-11-21 00:00:00', 1),
 ('1981-11-22 00:00:00', 2),
 ('1981-11-23 00:00:00', 2),
 ('1981-11-25 00:00:00', 1),
 ('1981-11-26 00:00:00', 3),
 ('1981-11-27 00:00:00', 2),
 ('1981-11-28 00:00:00', 1),
 ('1981-11-29 00:00:00', 1),
 ('1981-11-30 00:00:00', 2),
 ('1981-12-02 00:00:00', 1),
 ('1981-12-03 00:00:00', 3),
 ('1981-12-05 00:00:00', 1),
 ('1981-12-06 00:00:00', 2),
 ('1981-12-10 00:00:00', 4),
 ('1981-12-11 00:00:00', 4),
 ('1981-12-12 00:00:00', 2),
 ('1981-12-14 00:00:00', 1),
 ('1981-12-15 00:00:00', 3),
 ('1981-12-16 00:00:00', 2),
 ('1981-12-17 00:00:00', 3),
 ('1981-12-19 00:00:00', 2),
 ('1981-12-21 00:00:00', 3),
 ('1981-12-22 00:00:00', 1),
 ('1981-12-23 00:00:00', 1),
 ('1981-12-28 00:00:00', 3),
 ('1981-12-29 00:00:00', 1),
 ('1981-12-30 00:00:00', 2),
 ('1981-12-31 00:00:00', 2),
 ('1982-01-01 00:00:00', 3),
 ('1982-01-02 00:00:00', 1),
 ('1982-01-03 00:00:00', 1),
 ('1982-01-04 00:00:00', 1),
 ('1982-01-05 00:00:00', 4),
 ('1982-01-07 00:00:00', 1),
 ('1982-01-08 00:00:00', 3),
 ('1982-01-09 00:00:00', 1),
 ('1982-01-10 00:00:00', 1),
 ('1982-01-11 00:00:00', 2),
 ('1982-01-13 00:00:00', 2),
 ('1982-01-14 00:00:00', 1),
 ('1982-01-16 00:00:00', 2),
 ('1982-01-18 00:00:00', 3),
 ('1982-01-19 00:00:00', 1),
 ('1982-01-20 00:00:00', 1),
 ('1982-01-21 00:00:00', 3),
 ('1982-01-22 00:00:00', 3),
 ('1982-01-23 00:00:00', 1),
 ('1982-01-25 00:00:00', 2),
 ('1982-01-28 00:00:00', 1),
 ('1982-01-29 00:00:00', 2),
 ('1982-01-30 00:00:00', 2),
 ('1982-01-31 00:00:00', 4),
 ('1982-02-01 00:00:00', 3),
 ('1982-02-02 00:00:00', 1),
 ('1982-02-03 00:00:00', 2),
 ('1982-02-04 00:00:00', 2),
 ('1982-02-05 00:00:00', 2),
 ('1982-02-06 00:00:00', 1),
 ('1982-02-08 00:00:00', 1),
 ('1982-02-09 00:00:00', 1),
 ('1982-02-10 00:00:00', 1),
 ('1982-02-11 00:00:00', 3),
 ('1982-02-12 00:00:00', 2),
 ('1982-02-16 00:00:00', 2),
 ('1982-02-17 00:00:00', 2),
 ('1982-02-18 00:00:00', 3),
 ('1982-02-19 00:00:00', 2),
 ('1982-02-20 00:00:00', 2),
 ('1982-02-22 00:00:00', 2),
 ('1982-02-25 00:00:00', 3),
 ('1982-02-28 00:00:00', 1),
 ('1982-03-01 00:00:00', 4),
 ('1982-03-02 00:00:00', 3),
 ('1982-03-03 00:00:00', 2),
 ('1982-03-04 00:00:00', 1),
 ('1982-03-05 00:00:00', 2),
 ('1982-03-06 00:00:00', 1),
 ('1982-03-07 00:00:00', 1),
 ('1982-03-08 00:00:00', 2),
 ('1982-03-09 00:00:00', 1),
 ('1982-03-10 00:00:00', 2),
 ('1982-03-12 00:00:00', 1),
 ('1982-03-13 00:00:00', 1),
 ('1982-03-14 00:00:00', 1),
 ('1982-03-15 00:00:00', 2),
 ('1982-03-17 00:00:00', 1),
 ('1982-03-18 00:00:00', 2),
 ('1982-03-19 00:00:00', 3),
 ('1982-03-20 00:00:00', 4),
 ('1982-03-21 00:00:00', 1),
 ('1982-03-22 00:00:00', 1),
 ('1982-03-23 00:00:00', 1),
 ('1982-03-24 00:00:00', 1),
 ('1982-03-25 00:00:00', 1),
 ('1982-03-26 00:00:00', 2),
 ('1982-03-29 00:00:00', 1),
 ('1982-03-30 00:00:00', 3),
 ('1982-03-31 00:00:00', 1),
 ('1982-04-01 00:00:00', 3),
 ('1982-04-02 00:00:00', 1),
 ('1982-04-03 00:00:00', 2),
 ('1982-04-05 00:00:00', 2),
 ('1982-04-06 00:00:00', 2),
 ('1982-04-07 00:00:00', 1),
 ('1982-04-08 00:00:00', 2),
 ('1982-04-09 00:00:00', 2),
 ('1982-04-10 00:00:00', 3),
 ('1982-04-12 00:00:00', 1),
 ('1982-04-14 00:00:00', 3),
 ('1982-04-15 00:00:00', 2),
 ('1982-04-17 00:00:00', 4),
 ('1982-04-19 00:00:00', 1),
 ('1982-04-20 00:00:00', 2),
 ('1982-04-21 00:00:00', 1),
 ('1982-04-22 00:00:00', 3),
 ('1982-04-23 00:00:00', 1),
 ('1982-04-26 00:00:00', 2),
 ('1982-04-27 00:00:00', 2),
 ('1982-04-29 00:00:00', 3),
 ('1982-04-30 00:00:00', 1),
 ('1982-05-01 00:00:00', 2),
 ('1982-05-02 00:00:00', 2),
 ('1982-05-03 00:00:00', 1),
 ('1982-05-05 00:00:00', 3),
 ('1982-05-06 00:00:00', 1),
 ('1982-05-07 00:00:00', 3),
 ('1982-05-08 00:00:00', 3),
 ('1982-05-09 00:00:00', 2),
 ('1982-05-11 00:00:00', 1),
 ('1982-05-12 00:00:00', 1),
 ('1982-05-13 00:00:00', 4),
 ('1982-05-14 00:00:00', 3),
 ('1982-05-15 00:00:00', 2),
 ('1982-05-16 00:00:00', 1),
 ('1982-05-17 00:00:00', 2),
 ('1982-05-18 00:00:00', 1),
 ('1982-05-19 00:00:00', 1),
 ('1982-05-20 00:00:00', 3),
 ('1982-05-22 00:00:00', 1),
 ('1982-05-23 00:00:00', 1),
 ('1982-05-24 00:00:00', 4),
 ('1982-05-25 00:00:00', 4),
 ('1982-05-26 00:00:00', 3),
 ('1982-05-27 00:00:00', 1),
 ('1982-06-01 00:00:00', 3),
 ('1982-06-02 00:00:00', 1),
 ('1982-06-03 00:00:00', 1),
 ('1982-06-04 00:00:00', 2),
 ('1982-06-05 00:00:00', 2),
 ('1982-06-06 00:00:00', 2),
 ('1982-06-07 00:00:00', 2),
 ('1982-06-08 00:00:00', 1),
 ('1982-06-09 00:00:00', 1),
 ('1982-06-11 00:00:00', 1),
 ('1982-06-12 00:00:00', 1),
 ('1982-06-14 00:00:00', 1),
 ('1982-06-16 00:00:00', 2),
 ('1982-06-17 00:00:00', 2),
 ('1982-06-18 00:00:00', 3),
 ('1982-06-20 00:00:00', 1),
 ('1982-06-21 00:00:00', 1),
 ('1982-06-22 00:00:00', 1),
 ('1982-06-23 00:00:00', 1),
 ('1982-06-24 00:00:00', 3),
 ('1982-06-25 00:00:00', 2),
 ('1982-06-26 00:00:00', 1),
 ('1982-06-27 00:00:00', 2),
 ('1982-06-28 00:00:00', 1),
 ('1982-06-29 00:00:00', 2),
 ('1982-07-02 00:00:00', 1),
 ('1982-07-04 00:00:00', 1),
 ('1982-07-05 00:00:00', 4),
 ('1982-07-06 00:00:00', 1),
 ('1982-07-07 00:00:00', 1),
 ('1982-07-09 00:00:00', 1),
 ('1982-07-10 00:00:00', 3),
 ('1982-07-11 00:00:00', 1),
 ('1982-07-12 00:00:00', 1),
 ('1982-07-13 00:00:00', 2),
 ('1982-07-14 00:00:00', 3),
 ('1982-07-15 00:00:00', 2),
 ('1982-07-16 00:00:00', 1),
 ('1982-07-17 00:00:00', 2),
 ('1982-07-18 00:00:00', 1),
 ('1982-07-19 00:00:00', 1),
 ('1982-07-20 00:00:00', 1),
 ('1982-07-21 00:00:00', 1),
 ('1982-07-22 00:00:00', 1),
 ('1982-07-23 00:00:00', 1),
 ('1982-07-27 00:00:00', 2),
 ('1982-07-28 00:00:00', 2),
 ('1982-07-29 00:00:00', 1),
 ('1982-07-30 00:00:00', 1),
 ('1982-07-31 00:00:00', 2),
 ('1982-08-02 00:00:00', 3),
 ('1982-08-03 00:00:00', 2),
 ('1982-08-04 00:00:00', 2),
 ('1982-08-05 00:00:00', 4),
 ('1982-08-06 00:00:00', 2),
 ('1982-08-07 00:00:00', 1),
 ('1982-08-08 00:00:00', 1),
 ('1982-08-09 00:00:00', 1),
 ('1982-08-10 00:00:00', 1),
 ('1982-08-11 00:00:00', 2),
 ('1982-08-12 00:00:00', 3),

**Task 5 (0.5 point).** Calculate the mean and the standard deviation of the players' **height** with the name **Adriano**. <br>
**Note:** Name is represented by the first part of `player_name`.

In [ ]:
adriano_mean, adriano_std = # Your code here

**Task 6 (0.75 point).** How many players were born on each day of the week? Find the day of the week with the minimum number of players born.

In [ ]:
dow_with_min_players_born = # Your code here

**Task 7 (0.75 point).** Find a league with the most matches in total. If there are several leagues with the same amount of matches, take the first in the lexical order.

*Note*: Use league_data.csv and match_data.csv

In [ ]:
league_data = pd.read_csv("league_data.csv", index_col="Unnamed: 0")
match_data = pd.read_csv("match_data.csv", index_col="Unnamed: 0")

In [ ]:
league_data.head()

   league_id  country_id             league_name
0          1           1  Belgium Jupiler League
1       1729        1729  England Premier League
2       4769        4769          France Ligue 1
3       7809        7809   Germany 1. Bundesliga
4      10257       10257           Italy Serie A

In [ ]:
match_data.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [ ]:
league_most_matches = # Your code here

**Task 8 (1.25 point).** Find a player who participated in the largest number of matches during the whole match history. Assign a `player_name` to the given variable (use match_data['home_player_N', 'away_player_N'])

In [ ]:
max_matches_player = # Your code here

**Task 9 (1.5 point).** List top-5 tuples of most correlated **player's characteristics** in the descending order of the absolute [Pearson's coefficient](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient) value.

**Note 1:** Players characteristics are all the columns in `Player_Attributes` table except `[id, player_fifa_api_id, player_api_id, date, preferred_foot, attacking_work_rate, defensive_work_rate]`). <br>
**Note 2:** Exclude duplicated pairs from the list. E.g. ('gk_handling', 'gk_reflexes') and ('gk_reflexes', 'gk_handling') are duplicates, leave just one of them in the resulting list.

In [ ]:
player_attributes = pd.read_csv('player_attributes.csv', index_col="Unnamed: 0")

In [ ]:
player_attributes.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,63.0,41.0,45.0,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [ ]:
top_correlated_features = # Your code here

**Task 10 (2 points).** Find top-5 most similar players to **Neymar** whose names are given. The similarity is measured as [Euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) between vectors of players' characteristics (described in the task above). Put their names in a vector in ascending order by Euclidean distance and sorted by `player_name` if the distance is the same<br>
**Note 1:** There are many records for some players in the `Player_Attributes` table. You need to take the freshest data (characteristics with the most recent `date`). <br>
**Note 2:** Use pure values of the characteristics even if you are aware of such preprocessing technics as normalization. <br>
**Note 3:** Please avoid using any built-in methods for calculating the Euclidean distance between vectors, think about implementing your own.

In [ ]:
neymar_similarities = # Your code here

**Task 11 (1 point).** Calculate the number of home matches played by the **Borussia Dortmund** team in **Germany 1. Bundesliga** in season **2008/2009**

In [ ]:
team_data = pd.read_csv('team_data.csv', index_col="Unnamed: 0")

In [ ]:
team_data.head()

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB

In [ ]:
borussia_bundesliga_2008_2009_matches = # Your code here

**Task 12 (1 point).** Find a team having the most matches (both home and away!) in the **Germany 1. Bundesliga** in **2008/2009** season. Return number of matches.

In [ ]:
team_most_matches_bundesliga_2008_2009 = # Your code here

**Task 13 (1 point).** Count total number of **Arsenal** matches (both home and away!) in the **2015/2016** season which they have won. <br><br>
**Note:** Winning a game means scoring **more** goals than an opponent.

In [ ]:
arsenal_won_matches_2015_2016 = # Your code here

**Task 14 (2 points).** Find a team with the highest win rate in the **2015/2016** season. Win rate means won matches / all matches. If there are several teams with the highest win rate return the first by name in lexical order

In [ ]:
team_highest_winrate_2015_2016 = # Your code here

**Task 15 (2 points).** Determine the team with the maximum days' gap between matches in **England Premier League 2010/2011 season**. Return number of days in that gap. <br>
**Note**: a *gap* means the number of days between two consecutive matches of the same team.

In [ ]:
highest_gap_england_2010_2011 = # Your code here

### Warning! Do not change anything in the area below

In [ ]:
with open('student_answers.txt', 'w') as file:
    file.write(f"{players_180_190}\n")
    file.write(f"{players_1980}\n")
    file.write(f"{highest_players}\n")
    file.write(f"{years_born_players}\n")
    file.write(f"{round(adriano_mean, 3)} {round(adriano_std, 3)}\n")
    file.write(f"{dow_with_min_players_born}\n")
    file.write(f"{league_most_matches}\n")
    file.write(f"{max_matches_player}\n")
    file.write(f"{';'.join(['%s,%s' % tup for tup in top_correlated_features])};\n")
    file.write(f"{neymar_similarities}\n")
    file.write(f"{borussia_bundesliga_2008_2009_matches}\n")
    file.write(f"{team_most_matches_bundesliga_2008_2009}\n")
    file.write(f"{arsenal_won_matches_2015_2016}\n")
    file.write(f"{team_highest_winrate_2015_2016}\n")
    file.write(f"{highest_gap_england_2010_2011}\n")