<a href="https://colab.research.google.com/github/OleksiiLatypov/DRU_Data_Science_Fundamentals/blob/main/test_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to complete this assignment
Complete 15 graded tasks below.

- Do not delete or rename the variables given before the inscription `#your code here`.
- Do not change the code in the last Notebook cell, it is required for the server check.

## Some important notes
- If you need to **calculate the number of "something"** that means we expect you to assign an Integer to the given variable
- If you need to **make a list of "something"** we expect you to assign a Python list with appropriate values to the given variable
- If you need to find a **specifi—Å player, day of the week, team, etc.** we expect you to assign a String with the full name of the entity to the given variable (`player_name`, day of week full name, `team_name`, etc.)

In [2]:
import pandas as pd

pd.set_option('display.max_column', None)

In [3]:
player_data = pd.read_csv("player_data.csv", index_col="Unnamed: 0")

In [4]:
player_data.head()

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154

**Task 1 (0.25 point).** Calculate the number of players with a height between 180 and 190 inclusive

In [5]:
players_180_190 = player_data[player_data['height'].between(180, 190, inclusive='both')].shape[0]
players_180_190

5925

**Task 2 (0.25 point).** Calculate the number of players born in 1980. <br>

In [6]:
players_1980 = player_data[player_data['birthday'].apply(lambda x: x[:4] == '1980')].shape[0]
players_1980

434

**Task 3 (0.25 point).** Make a list of the top 10 players with the highest weight sorted in descending order. If there are several players with the same weight put them in the lexicographic order by name.

In [7]:
highest_players = player_data.sort_values(by=['weight', 'player_name'], ascending=[False, True]).head(10)
highest_players['player_name'].tolist()

['Kristof van Hout',
 'Tim Wiese',
 'Jeroen Verhoeven',
 'Ishmael Miller',
 'Cassio',
 'Christopher Samba',
 'Lars Unnerstall',
 'Marcus Hahnemann',
 'Abdoulaye Faye',
 'Enoch Showunmi']

**Task 4 (0.5 point).** Make a list of tuples containing years along with the number of players born in that year from 1980 up to 1990. <br>
**Structure example**: [(1980, 123), (1981, 140) ..., (1990, 83)] -> There were born 123 players in 1980, there were born 140 players in 1981 and etc.

In [8]:
players_1980_1990 = player_data[player_data['birthday'].apply(lambda x: 1980 <= int(x[:4]) <= 1990)]
new = players_1980_1990.copy()
new['birthday'] = new['birthday'].apply(lambda x: int(x[:4]))
players_by_year = new['birthday'].value_counts().sort_index()
years_born_players = list(zip(players_by_year.index, players_by_year))
years_born_players

[(1980, 434),
 (1981, 475),
 (1982, 487),
 (1983, 541),
 (1984, 607),
 (1985, 593),
 (1986, 710),
 (1987, 722),
 (1988, 802),
 (1989, 723),
 (1990, 696)]

**Task 5 (0.5 point).** Calculate the mean and the standard deviation of the players' **height** with the name **Adriano**. <br>
**Note:** Name is represented by the first part of `player_name`.

In [10]:
names = player_data[player_data['player_name'] == 'Adriano']

adriano_mean, adriano_std = names['height'].mean(), names['height'].std()
adriano_mean, adriano_std

(179.705, 6.9946145950533545)

**Task 6 (0.75 point).** How many players were born on each day of the week? Find the day of the week with the minimum number of players born.

In [11]:
formatted_data = player_data.copy()
formatted_data['birthday'] = pd.to_datetime(formatted_data['birthday'], format='%Y-%m-%d')
formatted_data['day_of_week'] = formatted_data['birthday'].dt.day_name()
players_by_day = formatted_data['day_of_week'].value_counts()
dow_with_min_players_born = players_by_day.idxmin()
dow_with_min_players_born

'Sunday'

**Task 7 (0.75 point).** Find a league with the most matches in total. If there are several leagues with the same amount of matches, take the first in the lexical order.

*Note*: Use league_data.csv and match_data.csv

In [12]:
league_data = pd.read_csv("league_data.csv", index_col="Unnamed: 0")
match_data = pd.read_csv("match_data.csv", index_col="Unnamed: 0")

In [13]:
league_data.head()

   league_id  country_id             league_name
0          1           1  Belgium Jupiler League
1       1729        1729  England Premier League
2       4769        4769          France Ligue 1
3       7809        7809   Germany 1. Bundesliga
4      10257       10257           Italy Serie A

In [14]:
match_data.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [15]:
total_games = match_data['league_id'].value_counts()
filtered_data = total_games[total_games == total_games.max()]
max_matches = list(filtered_data.keys())
res = []
for i in max_matches:
  res.extend(league_data['league_name'][league_data['league_id'] == i])
league_most_matches = sorted(res)[0]
league_most_matches

'England Premier League'

**Task 8 (1.25 point).** Find a player who participated in the largest number of matches during the whole match history. Assign a `player_name` to the given variable (use match_data['home_player_N', 'away_player_N'])

In [16]:
players = match_data[["home_player_1", "home_player_2", "home_player_3", "home_player_4",
                      "home_player_5","home_player_6","home_player_7", "home_player_8", "home_player_9",
                      "home_player_10","home_player_11",
                      "away_player_1", "away_player_2", "away_player_3","away_player_4","away_player_5",
                      "away_player_6","away_player_7","away_player_8", "away_player_9","away_player_10",
                      "away_player_11"]].stack()


player_counts = players.value_counts()
#display(player_counts.head(15))
most_participated_player = players.value_counts().idxmax()


max_matches_player = player_data.loc[player_data['player_api_id'] == most_participated_player, 'player_name'].iloc[0]
max_matches_player

'Steve Mandanda'

**Task 9 (1.5 point).** List top-5 tuples of most correlated **player's characteristics** in the descending order of the absolute [Pearson's coefficient](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient) value.

**Note 1:** Players characteristics are all the columns in `Player_Attributes` table except `[id, player_fifa_api_id, player_api_id, date, preferred_foot, attacking_work_rate, defensive_work_rate]`). <br>
**Note 2:** Exclude duplicated pairs from the list. E.g. ('gk_handling', 'gk_reflexes') and ('gk_reflexes', 'gk_handling') are duplicates, leave just one of them in the resulting list.

In [17]:
player_attributes = pd.read_csv('player_attributes.csv', index_col="Unnamed: 0")

In [18]:
player_attributes.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,63.0,41.0,45.0,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [19]:
import numpy as np

excluded_columns = ['id', 'player_fifa_api_id', 'player_api_id', 'date', 'preferred_foot', 'attacking_work_rate', 'defensive_work_rate']
player_characteristics = player_attributes.drop(columns=excluded_columns)

# Calculate the correlation matrix
correlation_matrix = player_characteristics.corr()

# Extract the upper triangle of the correlation matrix (excluding the diagonal)
upper_triangle = correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(bool))

# Get the top-5 correlated pairs in descending order of absolute correlation
top_correlations = (upper_triangle.abs().unstack().sort_values(ascending=False).drop_duplicates().head(5))
# Convert the top correlations into a list of tuples


top_correlated_features = [tuple(index) for index, value in top_correlations.items()]
top_correlated_features

[('gk_reflexes', 'gk_positioning'),
 ('gk_positioning', 'gk_handling'),
 ('gk_reflexes', 'gk_handling'),
 ('sliding_tackle', 'standing_tackle'),
 ('standing_tackle', 'marking')]

**Task 10 (2 points).** Find top-5 most similar players to **Neymar** whose names are given. The similarity is measured as [Euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) between vectors of players' characteristics (described in the task above). Put their names in a vector in ascending order by Euclidean distance and sorted by `player_name` if the distance is the same<br>
**Note 1:** There are many records for some players in the `Player_Attributes` table. You need to take the freshest data (characteristics with the most recent `date`). <br>
**Note 2:** Use pure values of the characteristics even if you are aware of such preprocessing technics as normalization. <br>
**Note 3:** Please avoid using any built-in methods for calculating the Euclidean distance between vectors, think about implementing your own.

In [20]:
neymar_data = player_data[player_data['player_name'] == 'Neymar']

# Merge Neymar's data with player_attributes

neymar_id = list(neymar_data['player_api_id'])[0]
print(neymar_id)
#neymar_rows = player_attributes[player_attributes['player_api_id'] == neymar_id]
#display(neymar_rows.head())


# Convert the 'date' column to datetime format
player_attributes['date'] = pd.to_datetime(player_attributes['date'])

# Find the index of the rows with the most recent date for each player
recent_data_indices = player_attributes.groupby('player_api_id')['date'].idxmax()

# Select the rows with the most recent date for each player
freshest_data = player_attributes.loc[recent_data_indices]

freshest_data

19533

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
139843,139844,148544,2625,2015-01-16,61.0,61.0,right,medium,medium,50.0,47.0,46.0,52.0,39.0,50.0,51.0,50.0,64.0,62.0,67.0,63.0,74.0,49.0,76.0,68.0,63.0,77.0,56.0,54.0,71.0,64.0,49.0,55.0,66.0,62.0,63.0,54.0,12.0,11.0,6.0,8.0,8.0
44144,44145,135819,2752,2015-10-16,72.0,72.0,right,medium,medium,39.0,40.0,82.0,59.0,23.0,41.0,33.0,19.0,61.0,57.0,32.0,34.0,34.0,64.0,39.0,60.0,54.0,62.0,85.0,20.0,84.0,71.0,34.0,55.0,38.0,72.0,74.0,67.0,12.0,7.0,8.0,10.0,16.0
88284,88285,110019,2768,2016-03-17,74.0,74.0,left,medium,medium,44.0,45.0,72.0,74.0,31.0,44.0,50.0,22.0,60.0,63.0,51.0,53.0,58.0,77.0,61.0,41.0,79.0,34.0,72.0,20.0,65.0,80.0,40.0,60.0,16.0,76.0,76.0,77.0,12.0,15.0,13.0,14.0,10.0
72141,72142,182861,2770,2013-07-05,69.0,69.0,right,medium,low,58.0,66.0,64.0,72.0,55.0,70.0,74.0,73.0,70.0,71.0,54.0,48.0,58.0,69.0,65.0,72.0,54.0,47.0,61.0,74.0,64.0,41.0,71.0,68.0,69.0,33.0,43.0,25.0,12.0,13.0,6.0,14.0,15.0
5121,5122,110809,2790,2010-08-30,67.0,77.0,left,None,7,72.0,37.0,51.0,64.0,43.0,64.0,67.0,56.0,62.0,65.0,69.0,72.0,65.0,64.0,67.0,46.0,61.0,56.0,67.0,42.0,74.0,68.0,56.0,60.0,54.0,70.0,73.0,69.0,8.0,14.0,8.0,13.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66601,66602,226508,744907,2016-06-09,53.0,67.0,left,medium,medium,43.0,45.0,48.0,60.0,43.0,57.0,47.0,44.0,59.0,56.0,66.0,64.0,61.0,54.0,74.0,51.0,63.0,54.0,51.0,39.0,37.0,23.0,49.0,52.0,53.0,40.0,49.0,50.0,9.0,14.0,13.0,12.0,9.0
58304,58305,233930,746419,2016-05-12,59.0,66.0,right,high,medium,55.0,28.0,50.0,35.0,29.0,67.0,37.0,39.0,35.0,55.0,77.0,76.0,70.0,60.0,74.0,29.0,55.0,63.0,46.0,27.0,59.0,53.0,55.0,40.0,43.0,55.0,69.0,62.0,7.0,10.0,7.0,9.0,9.0
60179,60180,233969,748432,2016-05-12,58.0,68.0,right,medium,medium,48.0,26.0,57.0,49.0,24.0,41.0,39.0,20.0,41.0,42.0,64.0,68.0,50.0,48.0,52.0,46.0,68.0,50.0,67.0,25.0,52.0,55.0,38.0,36.0,45.0,63.0,69.0,68.0,8.0,8.0,12.0,12.0,6.0
147408,147409,225462,750435,2016-04-14,60.0,74.0,right,medium,low,35.0,57.0,55.0,60.0,52.0,63.0,56.0,37.0,54.0,59.0,79.0,76.0,66.0,61.0,78.0,57.0,58.0,57.0,46.0,50.0,34.0,13.0,59.0,58.0,61.0,18.0,19.0,21.0,9.0,10.0,8.0,10.0,11.0
8085,8086,234141,750584,2016-05-19,58.0,66.0,right,medium,medium,47.0,39.0,53.0,60.0,37.0,54.0,40.0,45.0,55.0,56.0,63.0,60.0,51.0,54.0,76.0,59.0,58.0,55.0,57.0,38.0,62.0,56.0,41.0,47.0,52.0,56.0,66.0,62.0,8.0,9.0,13.0,11.0,13.0

**Task 11 (1 point).** Calculate the number of home matches played by the **Borussia Dortmund** team in **Germany 1. Bundesliga** in season **2008/2009**

In [21]:
team_data = pd.read_csv('team_data.csv', index_col="Unnamed: 0")

In [22]:
team_data.head()

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB

In [23]:
dortmund_id  = team_data[team_data["team_long_name"] == "Borussia Dortmund"] ["team_api_id"].values[0]
filtered_matches = match_data[
    (match_data["league_id"] == 7809)
    & (match_data["season"] == "2008/2009")
    & (match_data["home_team_api_id"] == dortmund_id)
]

borussia_bundesliga_2008_2009_matches = filtered_matches.shape[0]
borussia_bundesliga_2008_2009_matches

17

**Task 12 (1 point).** Find a team having the most matches (both home and away!) in the **Germany 1. Bundesliga** in **2008/2009** season. Return number of matches.

In [24]:
# filtered_matches = match_data[
#     (match_data["league_id"] == 7809)  # Replace with actual league ID
#     & (match_data["season"] == "2008/2009")
# ]

# filtered_matches["total_matches"] = (
#     filtered_matches.groupby("home_team_api_id")["id"].transform("size")
#     + filtered_matches.groupby("away_team_api_id")["id"].transform("size")
# )

# filtered_matches

# team_with_most_matches_id = filtered_matches["total_matches"].idxmax()
# most_matches = filtered_matches.loc[team_with_most_matches_id, "total_matches"]

# # Optionally, get team name
# most_active_team_name = team_data[team_data["team_api_id"] == team_with_most_matches_id]

# print("Team with most matches:", most_active_team_name)
# print("Number of matches:", most_matches)
#======================================================================
home_teams = pd.merge(match_data, team_data, left_on='home_team_api_id', right_on='team_api_id', how='inner')

# Merge team_data with match_data for away teams
away_teams = pd.merge(match_data, team_data, left_on='away_team_api_id', right_on='team_api_id', how='inner')

# Concatenate home_teams and away_teams to get all matches
all_matches = pd.concat([home_teams, away_teams])

# Filter matches for the Germany 1. Bundesliga in 2008/2009 season
germany_matches_0809 = all_matches[(all_matches['country_id'] == 7809) &
                                   (all_matches['season'] == '2008/2009')]

# Count the number of matches for each team
matches_count = germany_matches_0809['team_long_name'].value_counts()


team_most_matches_bundesliga_2008_2009 = matches_count.values[0]
matches_count.values[0]

34

**Task 13 (1 point).** Count total number of **Arsenal** matches (both home and away!) in the **2015/2016** season which they have won. <br><br>
**Note:** Winning a game means scoring **more** goals than an opponent.

In [46]:
arsenal_id  = team_data[team_data["team_long_name"] == "Arsenal"] ["team_api_id"].values[0]

arsenal_matches_2015_2016 = match_data[
    ((match_data['home_team_api_id'] == arsenal_id) | (match_data['away_team_api_id'] == arsenal_id)) &
    (match_data['season'] == '2015/2016')
]

total_wins = ((arsenal_matches_2015_2016['home_team_api_id'] == arsenal_id) & (arsenal_matches_2015_2016['home_team_goal'] > arsenal_matches_2015_2016['away_team_goal'])) | ((arsenal_matches_2015_2016['away_team_api_id'] == arsenal_id) & (arsenal_matches_2015_2016['away_team_goal'] > arsenal_matches_2015_2016['home_team_goal']))

total_wins_count = total_wins_count = total_wins.sum()

arsenal_won_matches_2015_2016 = total_wins_count

**Task 14 (2 points).** Find a team with the highest win rate in the **2015/2016** season. Win rate means won matches / all matches. If there are several teams with the highest win rate return the first by name in lexical order

In [63]:
relevant_columns = ['home_team_api_id', 'away_team_api_id', 'home_team_goal', 'away_team_goal']
match_data_teams = match_data[relevant_columns]

# Filter matches for the 2015/2016 season
matches_2015_2016 = match_data[match_data['season'] == '2015/2016']

# Calculate the total number of matches played by each team
matches_played = pd.concat([matches_2015_2016['home_team_api_id'], matches_2015_2016['away_team_api_id']], ignore_index=True)
matches_played_count = matches_played.value_counts()

# Calculate the number of matches won by each team
home_wins = matches_2015_2016[matches_2015_2016['home_team_goal'] > matches_2015_2016['away_team_goal']]['home_team_api_id']
away_wins = matches_2015_2016[matches_2015_2016['home_team_goal'] < matches_2015_2016['away_team_goal']]['away_team_api_id']
total_wins = pd.concat([home_wins, away_wins], ignore_index=True)
wins_count = total_wins.value_counts()

# Calculate the win rate for each team
win_rate = wins_count / matches_played_count
print(sorted(win_rate))
# Find the team with the highest win rate
team_with_highest_win_rate = win_rate.values[0]
print(team_with_highest_win_rate)
# Retrieve the team name from team_data
team_name = team_data.loc[team_data['team_api_id'] == team_with_highest_win_rate, 'team_long_name'].iloc[0]

# Display the result
print(f"The team with the highest win rate in the 2015/2016 season is: {team_name}")

#team_highest_winrate_2015_2016 = # Your code here

[0.07894736842105263, 0.07894736842105263, 0.20588235294117646, 0.21052631578947367, 0.23333333333333334, 0.23333333333333334, 0.23333333333333334, 0.23684210526315788, 0.23684210526315788, 0.23684210526315788, 0.23684210526315788, 0.2631578947368421, 0.2631578947368421, 0.2631578947368421, 0.2647058823529412, 0.2647058823529412, 0.2647058823529412, 0.2647058823529412, 0.2647058823529412, 0.26666666666666666, 0.26666666666666666, 0.2894736842105263, 0.2894736842105263, 0.2894736842105263, 0.2894736842105263, 0.2894736842105263, 0.29411764705882354, 0.29411764705882354, 0.29411764705882354, 0.3, 0.3157894736842105, 0.3157894736842105, 0.3157894736842105, 0.3157894736842105, 0.3157894736842105, 0.3235294117647059, 0.3333333333333333, 0.3333333333333333, 0.3333333333333333, 0.34210526315789475, 0.34210526315789475, 0.35294117647058826, 0.3684210526315789, 0.3684210526315789, 0.3684210526315789, 0.39473684210526316, 0.4, 0.4, 0.4117647058823529, 0.4117647058823529, 0.42105263157894735, 0.42105263157894735, 0.42105263157894735, 0.4411764705882353, 0.4473684210526316, 0.4473684210526316, 0.4666666666666667, 0.4666666666666667, 0.47368421052631576, 0.47368421052631576, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5263157894736842, 0.5294117647058824, 0.5666666666666667, 0.6052631578947368, 0.7, 0.7058823529411765, 0.7894736842105263, 0.8235294117647058]
0.23333333333333334

IndexError: ignored

**Task 15 (2 points).** Determine the team with the maximum days' gap between matches in **England Premier League 2010/2011 season**. Return number of days in that gap. <br>
**Note**: a *gap* means the number of days between two consecutive matches of the same team.

In [ ]:
highest_gap_england_2010_2011 = # Your code here

### Warning! Do not change anything in the area below

In [ ]:
with open('student_answers.txt', 'w') as file:
    file.write(f"{players_180_190}\n")
    file.write(f"{players_1980}\n")
    file.write(f"{highest_players}\n")
    file.write(f"{years_born_players}\n")
    file.write(f"{round(adriano_mean, 3)} {round(adriano_std, 3)}\n")
    file.write(f"{dow_with_min_players_born}\n")
    file.write(f"{league_most_matches}\n")
    file.write(f"{max_matches_player}\n")
    file.write(f"{';'.join(['%s,%s' % tup for tup in top_correlated_features])};\n")
    file.write(f"{neymar_similarities}\n")
    file.write(f"{borussia_bundesliga_2008_2009_matches}\n")
    file.write(f"{team_most_matches_bundesliga_2008_2009}\n")
    file.write(f"{arsenal_won_matches_2015_2016}\n")
    file.write(f"{team_highest_winrate_2015_2016}\n")
    file.write(f"{highest_gap_england_2010_2011}\n")